package com.shoulaxiao.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book_type
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class bookTypeDO {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   书籍类型code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.type_code
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     * Database Column Remarks:
     *   书籍类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.id
     *
     * @return the value of book_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.id
     *
     * @param id the value for book_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.type_code
     *
     * @return the value of book_type.type_code
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.type_code
     *
     * @param typeCode the value for book_type.type_code
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.type_name
     *
     * @return the value of book_type.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.type_name
     *
     * @param typeName the value for book_type.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.create_time
     *
     * @return the value of book_type.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.create_time
     *
     * @param createTime the value for book_type.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.update_time
     *
     * @return the value of book_type.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.update_time
     *
     * @param updateTime the value for book_type.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}