package com.shoulaxiao.dao;

import com.shoulaxiao.entity.bookTypeDO;
import com.shoulaxiao.entity.bookTypeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface bookTypeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    long countByExample(bookTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int deleteByExample(bookTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int insert(bookTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int insertSelective(bookTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    List<bookTypeDO> selectByExample(bookTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    bookTypeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") bookTypeDO record, @Param("example") bookTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") bookTypeDO record, @Param("example") bookTypeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(bookTypeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(bookTypeDO record);
}